name: React Todo CI

on:
  push:
    branches:
      - "*"

jobs:
  install-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}  🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install Dependencies  🔧
        run: yarn

      - name: Run Test  🔧
        run: yarn test
